In [12]:
import pandas as pd
import csv

In [13]:
unem_csv = pd.read_csv("unemployment_data.csv")

In [14]:
unem_csv

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
0,Last Updated Date,2019-06-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2009.000000,2010.000000,2011.000000,2012.000000,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000
3,Aruba,ABW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.470000,2.275000,1.984000,1.692000,1.725000,1.735000,1.679000,1.634000,1.559000,1.542000
5,Angola,AGO,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.609000,9.089000,7.362000,7.359000,7.454000,7.429000,7.279000,7.281000,7.139000,7.253000
6,Albania,ALB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,13.674000,14.086000,13.481000,13.376000,15.866000,17.490000,17.080000,15.220000,13.750000,13.898000
7,Andorra,AND,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Arab World,ARB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.259066,9.178180,10.037677,10.233833,10.219504,10.218629,10.220711,9.967000,9.956021,9.942483
9,United Arab Emirates,ARE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.699000,2.663000,2.494000,2.409000,2.292000,2.061000,1.836000,1.636000,2.463000,2.575000
10,Argentina,ARG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.645000,7.714000,7.179000,7.217000,7.100000,7.268000,7.643000,8.016000,8.347000,9.483000
11,Armenia,ARM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.740000,19.007999,18.443001,17.309999,16.179001,17.497999,18.261000,17.617001,17.827000,17.712000
12,American Samoa,ASM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Antigua and Barbuda,ATG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Australia,AUS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.561000,5.211000,5.081000,5.224000,5.663000,6.078000,6.056000,5.711000,5.594000,5.387000
15,Austria,AUT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.301000,4.820000,4.564000,4.865000,5.335000,5.620000,5.723000,6.014000,5.499000,4.786000
16,Azerbaijan,AZE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.740000,5.630000,5.420000,5.190000,4.970000,4.910000,4.960000,5.000000,5.000000,5.220000
17,Burundi,BDI,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.795000,1.800000,1.766000,1.712000,1.674000,1.570000,1.592000,1.566000,1.501000,1.528000
18,Belgium,BEL,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.908000,8.292000,7.140000,7.542000,8.425000,8.523000,8.482000,7.830000,7.086000,6.323000
19,Benin,BEN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.967000,1.040000,2.646000,2.735000,2.666000,2.541000,2.463000,2.419000,2.180000,2.125000
20,Burkina Faso,BFA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.397000,4.909000,5.293000,5.809000,6.278000,6.479000,6.704000,6.364000,6.015000,6.059000
21,Bangladesh,BGD,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,3.379000,3.718000,4.048000,4.426000,4.411000,4.416000,4.350000,4.372000,4.308000
22,Bulgaria,BGR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.817000,10.279000,11.260000,12.270000,12.941000,11.424000,9.143000,7.575000,6.164000,5.261000
23,Bahrain,BHR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.069000,1.130000,1.140000,1.200000,1.216000,1.149000,1.076000,1.013000,0.947000,0.962000
24,"Bahamas, The",BHS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,14.250000,14.540000,14.520000,14.020000,16.180000,13.800000,12.000000,12.700000,12.381000,11.850000
25,Bosnia and Herzegovina,BIH,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,24.068001,27.312000,27.582001,28.010000,27.450001,27.517000,27.650000,25.410000,20.469999,20.839001
26,Belarus,BLR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.100000,6.061000,6.075000,6.038000,5.935000,5.893000,5.913000,5.840000,5.650000,5.708000
27,Belize,BLZ,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.115000,11.659000,12.758000,14.270000,11.700000,11.570000,9.970000,7.910000,9.000000,9.368000
28,Bermuda,BMU,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Bolivia,BOL,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.863000,2.577000,2.219000,2.048000,2.394000,2.007000,3.066000,3.056000,3.233000,3.258000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,Latin America & the Caribbean (IDA & IBRD coun...,TLA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.666859,7.064313,6.522478,6.413785,6.338548,6.150531,6.685651,7.858384,8.161817,8.137898
238,Timor-Leste,TLS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.180000,3.301000,3.201000,3.249000,3.326000,3.288000,3.343000,2.979000,2.963000,2.999000
239,Middle East & North Africa (IDA & IBRD countries),TMN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.347877,10.634479,11.415288,11.717683,11.212578,11.239425,11.450745,11.514831,11.389468,11.293507
240,Tonga,TON,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.125000,1.146000,1.134000,1.113000,1.135000,1.110000,1.080000,1.055000,1.003000,1.027000
241,South Asia (IDA & IBRD),TSA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.552167,2.368484,2.452512,2.689762,2.962370,2.798306,2.992566,2.929176,2.773212,2.750178
242,Sub-Saharan Africa (IDA & IBRD countries),TSS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.190139,6.322814,6.160723,6.024351,5.925104,5.896349,6.073460,6.249682,6.120978,6.096124
243,Trinidad and Tobago,TTO,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.648000,3.775000,3.248000,3.453000,2.460000,2.224000,2.211000,2.972000,2.817000,2.830000
244,Tunisia,TUN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,13.291000,13.049000,18.334000,17.629999,15.934000,15.058000,15.218000,15.514000,15.379000,15.478000
245,Turkey,TUR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,12.552000,10.660000,8.796000,8.149000,8.732000,9.880000,10.236000,10.839000,10.819000,10.895000
246,Tuvalu,TUV,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,Tanzania,TZA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.500000,3.035000,3.470000,3.240000,2.930000,2.125000,2.123000,2.095000,1.939000,1.932000
248,Uganda,UGA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.600000,3.680000,3.595000,3.551000,1.910000,1.888000,1.870000,1.792000,1.698000,1.742000
249,Ukraine,UKR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.840000,8.100000,7.860000,7.530000,7.170000,9.270000,9.140000,9.350000,9.510000,9.381000
250,Upper middle income,UMC,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.157953,5.893072,5.701646,5.690786,5.652736,5.615200,5.799850,6.054581,6.061633,6.049054
251,Uruguay,URY,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.740000,7.158000,6.307000,6.451000,6.444000,6.547000,7.488000,7.841000,7.890000,7.961000
252,United States,USA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.254000,9.633000,8.949000,8.069000,7.375000,6.168000,5.280000,4.869000,4.355000,3.933000
253,Uzbekistan,UZB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.040000,5.360000,4.960000,4.870000,4.860000,5.090000,5.150000,5.160000,4.972000,5.223000
254,St. Vincent and the Grenadines,VCT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,19.752001,19.916000,19.791000,19.719999,19.691000,19.687000,20.198999,20.065001,19.731001,19.761000
255,"Venezuela, RB",VEN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.050000,8.450000,6.902000,6.601000,7.540000,6.950000,6.820000,7.460000,7.422000,8.365000
256,British Virgin Islands,VGB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,Virgin Islands (U.S.),VIR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.050000,9.242000,9.201000,9.309000,9.358000,9.154000,8.923000,8.706000,8.462000,8.410000
258,Vietnam,VNM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.737000,1.114000,0.999000,1.027000,1.252000,1.256000,1.859000,1.851000,1.886000,1.891000
259,Vanuatu,VUT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.460000,5.636000,5.888000,6.051000,5.991000,5.870000,5.526000,5.694000,5.423000,5.409000
260,World,WLD,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.598770,5.474486,5.343200,5.351460,5.352923,5.189820,5.216667,5.215801,5.050056,4.953513
261,Samoa,WSM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.345000,5.524000,5.680000,8.752000,8.796000,8.720000,8.616000,8.606000,8.324000,8.325000
262,Kosovo,XKX,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,"Yemen, Rep.",YEM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,12.513000,12.905000,13.058000,13.252000,13.507000,13.467000,14.023000,13.524000,13.175000,12.934000
264,South Africa,ZAF,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.538000,24.693001,24.653000,24.732000,24.569000,24.898001,25.156000,26.551001,27.327000,26.958000
265,Zambia,ZMB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.623000,13.190000,10.200000,7.850000,7.801000,7.707000,7.446000,7.372000,7.206000,7.209000
266,Zimbabwe,ZWE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.034000,5.122000,5.368000,5.608000,5.623000,5.518000,5.438000,5.239000,4.943000,4.915000

In [15]:
unem_csv = unem_csv.drop([0,1])
unem_csv

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2009.000000,2010.000000,2011.000000,2012.000000,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000
3,Aruba,ABW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.470000,2.275000,1.984000,1.692000,1.725000,1.735000,1.679000,1.634000,1.559000,1.542000
5,Angola,AGO,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.609000,9.089000,7.362000,7.359000,7.454000,7.429000,7.279000,7.281000,7.139000,7.253000
6,Albania,ALB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,13.674000,14.086000,13.481000,13.376000,15.866000,17.490000,17.080000,15.220000,13.750000,13.898000
7,Andorra,AND,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Arab World,ARB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.259066,9.178180,10.037677,10.233833,10.219504,10.218629,10.220711,9.967000,9.956021,9.942483
9,United Arab Emirates,ARE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.699000,2.663000,2.494000,2.409000,2.292000,2.061000,1.836000,1.636000,2.463000,2.575000
10,Argentina,ARG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.645000,7.714000,7.179000,7.217000,7.100000,7.268000,7.643000,8.016000,8.347000,9.483000
11,Armenia,ARM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.740000,19.007999,18.443001,17.309999,16.179001,17.497999,18.261000,17.617001,17.827000,17.712000
12,American Samoa,ASM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Antigua and Barbuda,ATG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Australia,AUS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.561000,5.211000,5.081000,5.224000,5.663000,6.078000,6.056000,5.711000,5.594000,5.387000
15,Austria,AUT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.301000,4.820000,4.564000,4.865000,5.335000,5.620000,5.723000,6.014000,5.499000,4.786000
16,Azerbaijan,AZE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.740000,5.630000,5.420000,5.190000,4.970000,4.910000,4.960000,5.000000,5.000000,5.220000
17,Burundi,BDI,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.795000,1.800000,1.766000,1.712000,1.674000,1.570000,1.592000,1.566000,1.501000,1.528000
18,Belgium,BEL,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.908000,8.292000,7.140000,7.542000,8.425000,8.523000,8.482000,7.830000,7.086000,6.323000
19,Benin,BEN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.967000,1.040000,2.646000,2.735000,2.666000,2.541000,2.463000,2.419000,2.180000,2.125000
20,Burkina Faso,BFA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.397000,4.909000,5.293000,5.809000,6.278000,6.479000,6.704000,6.364000,6.015000,6.059000
21,Bangladesh,BGD,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,3.379000,3.718000,4.048000,4.426000,4.411000,4.416000,4.350000,4.372000,4.308000
22,Bulgaria,BGR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.817000,10.279000,11.260000,12.270000,12.941000,11.424000,9.143000,7.575000,6.164000,5.261000
23,Bahrain,BHR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.069000,1.130000,1.140000,1.200000,1.216000,1.149000,1.076000,1.013000,0.947000,0.962000
24,"Bahamas, The",BHS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,14.250000,14.540000,14.520000,14.020000,16.180000,13.800000,12.000000,12.700000,12.381000,11.850000
25,Bosnia and Herzegovina,BIH,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,24.068001,27.312000,27.582001,28.010000,27.450001,27.517000,27.650000,25.410000,20.469999,20.839001
26,Belarus,BLR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.100000,6.061000,6.075000,6.038000,5.935000,5.893000,5.913000,5.840000,5.650000,5.708000
27,Belize,BLZ,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.115000,11.659000,12.758000,14.270000,11.700000,11.570000,9.970000,7.910000,9.000000,9.368000
28,Bermuda,BMU,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Bolivia,BOL,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.863000,2.577000,2.219000,2.048000,2.394000,2.007000,3.066000,3.056000,3.233000,3.258000
30,Brazil,BRA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.522000,7.726000,6.917000,7.193000,6.985000,6.670000,8.437000,11.609000,12.827000,12.544000
31,Barbados,BRB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.020000,10.690000,11.190000,11.590000,11.550000,12.170000,11.350000,9.720000,9.487000,9.568000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,Latin America & the Caribbean (IDA & IBRD coun...,TLA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.666859,7.064313,6.522478,6.413785,6.338548,6.150531,6.685651,7.858384,8.161817,8.137898
238,Timor-Leste,TLS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.180000,3.301000,3.201000,3.249000,3.326000,3.288000,3.343000,2.979000,2.963000,2.999000
239,Middle East & North Africa (IDA & IBRD countries),TMN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.347877,10.634479,11.415288,11.717683,11.212578,11.239425,11.450745,11.514831,11.389468,11.293507
240,Tonga,TON,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.125000,1.146000,1.134000,1.113000,1.135000,1.110000,1.080000,1.055000,1.003000,1.027000
241,South Asia (IDA & IBRD),TSA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.552167,2.368484,2.452512,2.689762,2.962370,2.798306,2.992566,2.929176,2.773212,2.750178
242,Sub-Saharan Africa (IDA & IBRD countries),TSS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.190139,6.322814,6.160723,6.024351,5.925104,5.896349,6.073460,6.249682,6.120978,6.096124
243,Trinidad and Tobago,TTO,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.648000,3.775000,3.248000,3.453000,2.460000,2.224000,2.211000,2.972000,2.817000,2.830000
244,Tunisia,TUN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,13.291000,13.049000,18.334000,17.629999,15.934000,15.058000,15.218000,15.514000,15.379000,15.478000
245,Turkey,TUR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,12.552000,10.660000,8.796000,8.149000,8.732000,9.880000,10.236000,10.839000,10.819000,10.895000
246,Tuvalu,TUV,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,Tanzania,TZA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.500000,3.035000,3.470000,3.240000,2.930000,2.125000,2.123000,2.095000,1.939000,1.932000
248,Uganda,UGA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.600000,3.680000,3.595000,3.551000,1.910000,1.888000,1.870000,1.792000,1.698000,1.742000
249,Ukraine,UKR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.840000,8.100000,7.860000,7.530000,7.170000,9.270000,9.140000,9.350000,9.510000,9.381000
250,Upper middle income,UMC,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.157953,5.893072,5.701646,5.690786,5.652736,5.615200,5.799850,6.054581,6.061633,6.049054
251,Uruguay,URY,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.740000,7.158000,6.307000,6.451000,6.444000,6.547000,7.488000,7.841000,7.890000,7.961000
252,United States,USA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.254000,9.633000,8.949000,8.069000,7.375000,6.168000,5.280000,4.869000,4.355000,3.933000
253,Uzbekistan,UZB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.040000,5.360000,4.960000,4.870000,4.860000,5.090000,5.150000,5.160000,4.972000,5.223000
254,St. Vincent and the Grenadines,VCT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,19.752001,19.916000,19.791000,19.719999,19.691000,19.687000,20.198999,20.065001,19.731001,19.761000
255,"Venezuela, RB",VEN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.050000,8.450000,6.902000,6.601000,7.540000,6.950000,6.820000,7.460000,7.422000,8.365000
256,British Virgin Islands,VGB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,Virgin Islands (U.S.),VIR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.050000,9.242000,9.201000,9.309000,9.358000,9.154000,8.923000,8.706000,8.462000,8.410000
258,Vietnam,VNM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.737000,1.114000,0.999000,1.027000,1.252000,1.256000,1.859000,1.851000,1.886000,1.891000
259,Vanuatu,VUT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.460000,5.636000,5.888000,6.051000,5.991000,5.870000,5.526000,5.694000,5.423000,5.409000
260,World,WLD,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.598770,5.474486,5.343200,5.351460,5.352923,5.189820,5.216667,5.215801,5.050056,4.953513
261,Samoa,WSM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.345000,5.524000,5.680000,8.752000,8.796000,8.720000,8.616000,8.606000,8.324000,8.325000
262,Kosovo,XKX,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,"Yemen, Rep.",YEM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,12.513000,12.905000,13.058000,13.252000,13.507000,13.467000,14.023000,13.524000,13.175000,12.934000
264,South Africa,ZAF,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.538000,24.693001,24.653000,24.732000,24.569000,24.898001,25.156000,26.551001,27.327000,26.958000
265,Zambia,ZMB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.623000,13.190000,10.200000,7.850000,7.801000,7.707000,7.446000,7.372000,7.206000,7.209000
266,Zimbabwe,ZWE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.034000,5.122000,5.368000,5.608000,5.623000,5.518000,5.438000,5.239000,4.943000,4.915000

In [16]:
unem_csv.columns = unem_csv.iloc[0]
unem_csv

2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2009.000000,2010.000000,2011.000000,2012.000000,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000
3,Aruba,ABW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.470000,2.275000,1.984000,1.692000,1.725000,1.735000,1.679000,1.634000,1.559000,1.542000
5,Angola,AGO,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.609000,9.089000,7.362000,7.359000,7.454000,7.429000,7.279000,7.281000,7.139000,7.253000
6,Albania,ALB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,13.674000,14.086000,13.481000,13.376000,15.866000,17.490000,17.080000,15.220000,13.750000,13.898000
7,Andorra,AND,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Arab World,ARB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.259066,9.178180,10.037677,10.233833,10.219504,10.218629,10.220711,9.967000,9.956021,9.942483
9,United Arab Emirates,ARE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.699000,2.663000,2.494000,2.409000,2.292000,2.061000,1.836000,1.636000,2.463000,2.575000
10,Argentina,ARG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.645000,7.714000,7.179000,7.217000,7.100000,7.268000,7.643000,8.016000,8.347000,9.483000
11,Armenia,ARM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.740000,19.007999,18.443001,17.309999,16.179001,17.497999,18.261000,17.617001,17.827000,17.712000
12,American Samoa,ASM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Antigua and Barbuda,ATG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Australia,AUS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.561000,5.211000,5.081000,5.224000,5.663000,6.078000,6.056000,5.711000,5.594000,5.387000
15,Austria,AUT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.301000,4.820000,4.564000,4.865000,5.335000,5.620000,5.723000,6.014000,5.499000,4.786000
16,Azerbaijan,AZE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.740000,5.630000,5.420000,5.190000,4.970000,4.910000,4.960000,5.000000,5.000000,5.220000
17,Burundi,BDI,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.795000,1.800000,1.766000,1.712000,1.674000,1.570000,1.592000,1.566000,1.501000,1.528000
18,Belgium,BEL,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.908000,8.292000,7.140000,7.542000,8.425000,8.523000,8.482000,7.830000,7.086000,6.323000
19,Benin,BEN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.967000,1.040000,2.646000,2.735000,2.666000,2.541000,2.463000,2.419000,2.180000,2.125000
20,Burkina Faso,BFA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.397000,4.909000,5.293000,5.809000,6.278000,6.479000,6.704000,6.364000,6.015000,6.059000
21,Bangladesh,BGD,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,3.379000,3.718000,4.048000,4.426000,4.411000,4.416000,4.350000,4.372000,4.308000
22,Bulgaria,BGR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.817000,10.279000,11.260000,12.270000,12.941000,11.424000,9.143000,7.575000,6.164000,5.261000
23,Bahrain,BHR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.069000,1.130000,1.140000,1.200000,1.216000,1.149000,1.076000,1.013000,0.947000,0.962000
24,"Bahamas, The",BHS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,14.250000,14.540000,14.520000,14.020000,16.180000,13.800000,12.000000,12.700000,12.381000,11.850000
25,Bosnia and Herzegovina,BIH,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,24.068001,27.312000,27.582001,28.010000,27.450001,27.517000,27.650000,25.410000,20.469999,20.839001
26,Belarus,BLR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.100000,6.061000,6.075000,6.038000,5.935000,5.893000,5.913000,5.840000,5.650000,5.708000
27,Belize,BLZ,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.115000,11.659000,12.758000,14.270000,11.700000,11.570000,9.970000,7.910000,9.000000,9.368000
28,Bermuda,BMU,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Bolivia,BOL,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.863000,2.577000,2.219000,2.048000,2.394000,2.007000,3.066000,3.056000,3.233000,3.258000
30,Brazil,BRA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.522000,7.726000,6.917000,7.193000,6.985000,6.670000,8.437000,11.609000,12.827000,12.544000
31,Barbados,BRB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.020000,10.690000,11.190000,11.590000,11.550000,12.170000,11.350000,9.720000,9.487000,9.568000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,Latin America & the Caribbean (IDA & IBRD coun...,TLA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.666859,7.064313,6.522478,6.413785,6.338548,6.150531,6.685651,7.858384,8.161817,8.137898
238,Timor-Leste,TLS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.180000,3.301000,3.201000,3.249000,3.326000,3.288000,3.343000,2.979000,2.963000,2.999000
239,Middle East & North Africa (IDA & IBRD countries),TMN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.347877,10.634479,11.415288,11.717683,11.212578,11.239425,11.450745,11.514831,11.389468,11.293507
240,Tonga,TON,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.125000,1.146000,1.134000,1.113000,1.135000,1.110000,1.080000,1.055000,1.003000,1.027000
241,South Asia (IDA & IBRD),TSA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.552167,2.368484,2.452512,2.689762,2.962370,2.798306,2.992566,2.929176,2.773212,2.750178
242,Sub-Saharan Africa (IDA & IBRD countries),TSS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.190139,6.322814,6.160723,6.024351,5.925104,5.896349,6.073460,6.249682,6.120978,6.096124
243,Trinidad and Tobago,TTO,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.648000,3.775000,3.248000,3.453000,2.460000,2.224000,2.211000,2.972000,2.817000,2.830000
244,Tunisia,TUN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,13.291000,13.049000,18.334000,17.629999,15.934000,15.058000,15.218000,15.514000,15.379000,15.478000
245,Turkey,TUR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,12.552000,10.660000,8.796000,8.149000,8.732000,9.880000,10.236000,10.839000,10.819000,10.895000
246,Tuvalu,TUV,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,Tanzania,TZA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.500000,3.035000,3.470000,3.240000,2.930000,2.125000,2.123000,2.095000,1.939000,1.932000
248,Uganda,UGA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.600000,3.680000,3.595000,3.551000,1.910000,1.888000,1.870000,1.792000,1.698000,1.742000
249,Ukraine,UKR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.840000,8.100000,7.860000,7.530000,7.170000,9.270000,9.140000,9.350000,9.510000,9.381000
250,Upper middle income,UMC,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.157953,5.893072,5.701646,5.690786,5.652736,5.615200,5.799850,6.054581,6.061633,6.049054
251,Uruguay,URY,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.740000,7.158000,6.307000,6.451000,6.444000,6.547000,7.488000,7.841000,7.890000,7.961000
252,United States,USA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.254000,9.633000,8.949000,8.069000,7.375000,6.168000,5.280000,4.869000,4.355000,3.933000
253,Uzbekistan,UZB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.040000,5.360000,4.960000,4.870000,4.860000,5.090000,5.150000,5.160000,4.972000,5.223000
254,St. Vincent and the Grenadines,VCT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,19.752001,19.916000,19.791000,19.719999,19.691000,19.687000,20.198999,20.065001,19.731001,19.761000
255,"Venezuela, RB",VEN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.050000,8.450000,6.902000,6.601000,7.540000,6.950000,6.820000,7.460000,7.422000,8.365000
256,British Virgin Islands,VGB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,Virgin Islands (U.S.),VIR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.050000,9.242000,9.201000,9.309000,9.358000,9.154000,8.923000,8.706000,8.462000,8.410000
258,Vietnam,VNM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.737000,1.114000,0.999000,1.027000,1.252000,1.256000,1.859000,1.851000,1.886000,1.891000
259,Vanuatu,VUT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.460000,5.636000,5.888000,6.051000,5.991000,5.870000,5.526000,5.694000,5.423000,5.409000
260,World,WLD,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.598770,5.474486,5.343200,5.351460,5.352923,5.189820,5.216667,5.215801,5.050056,4.953513
261,Samoa,WSM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.345000,5.524000,5.680000,8.752000,8.796000,8.720000,8.616000,8.606000,8.324000,8.325000
262,Kosovo,XKX,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,"Yemen, Rep.",YEM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,12.513000,12.905000,13.058000,13.252000,13.507000,13.467000,14.023000,13.524000,13.175000,12.934000
264,South Africa,ZAF,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.538000,24.693001,24.653000,24.732000,24.569000,24.898001,25.156000,26.551001,27.327000,26.958000
265,Zambia,ZMB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.623000,13.190000,10.200000,7.850000,7.801000,7.707000,7.446000,7.372000,7.206000,7.209000
266,Zimbabwe,ZWE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.034000,5.122000,5.368000,5.608000,5.623000,5.518000,5.438000,5.239000,4.943000,4.915000

In [17]:
unem_csv = unem_csv.drop([2])

In [18]:
unem_csv = unem_csv.set_index(['Country Name'],drop = True)

In [19]:
unem_csv

2,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,1966.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,AFG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.470000,2.275000,1.984000,1.692000,1.725000,1.735000,1.679000,1.634000,1.559000,1.542000
Angola,AGO,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.609000,9.089000,7.362000,7.359000,7.454000,7.429000,7.279000,7.281000,7.139000,7.253000
Albania,ALB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.674000,14.086000,13.481000,13.376000,15.866000,17.490000,17.080000,15.220000,13.750000,13.898000
Andorra,AND,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World,ARB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.259066,9.178180,10.037677,10.233833,10.219504,10.218629,10.220711,9.967000,9.956021,9.942483
United Arab Emirates,ARE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.699000,2.663000,2.494000,2.409000,2.292000,2.061000,1.836000,1.636000,2.463000,2.575000
Argentina,ARG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.645000,7.714000,7.179000,7.217000,7.100000,7.268000,7.643000,8.016000,8.347000,9.483000
Armenia,ARM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.740000,19.007999,18.443001,17.309999,16.179001,17.497999,18.261000,17.617001,17.827000,17.712000
American Samoa,ASM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Antigua and Barbuda,ATG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Australia,AUS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.561000,5.211000,5.081000,5.224000,5.663000,6.078000,6.056000,5.711000,5.594000,5.387000
Austria,AUT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.301000,4.820000,4.564000,4.865000,5.335000,5.620000,5.723000,6.014000,5.499000,4.786000
Azerbaijan,AZE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.740000,5.630000,5.420000,5.190000,4.970000,4.910000,4.960000,5.000000,5.000000,5.220000
Burundi,BDI,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.795000,1.800000,1.766000,1.712000,1.674000,1.570000,1.592000,1.566000,1.501000,1.528000
Belgium,BEL,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.908000,8.292000,7.140000,7.542000,8.425000,8.523000,8.482000,7.830000,7.086000,6.323000
Benin,BEN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.967000,1.040000,2.646000,2.735000,2.666000,2.541000,2.463000,2.419000,2.180000,2.125000
Burkina Faso,BFA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.397000,4.909000,5.293000,5.809000,6.278000,6.479000,6.704000,6.364000,6.015000,6.059000
Bangladesh,BGD,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,3.379000,3.718000,4.048000,4.426000,4.411000,4.416000,4.350000,4.372000,4.308000
Bulgaria,BGR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.817000,10.279000,11.260000,12.270000,12.941000,11.424000,9.143000,7.575000,6.164000,5.261000
Bahrain,BHR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.069000,1.130000,1.140000,1.200000,1.216000,1.149000,1.076000,1.013000,0.947000,0.962000
"Bahamas, The",BHS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.250000,14.540000,14.520000,14.020000,16.180000,13.800000,12.000000,12.700000,12.381000,11.850000
Bosnia and Herzegovina,BIH,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.068001,27.312000,27.582001,28.010000,27.450001,27.517000,27.650000,25.410000,20.469999,20.839001
Belarus,BLR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.100000,6.061000,6.075000,6.038000,5.935000,5.893000,5.913000,5.840000,5.650000,5.708000
Belize,BLZ,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.115000,11.659000,12.758000,14.270000,11.700000,11.570000,9.970000,7.910000,9.000000,9.368000
Bermuda,BMU,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bolivia,BOL,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.863000,2.577000,2.219000,2.048000,2.394000,2.007000,3.066000,3.056000,3.233000,3.258000
Brazil,BRA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.522000,7.726000,6.917000,7.193000,6.985000,6.670000,8.437000,11.609000,12.827000,12.544000
Barbados,BRB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.020000,10.690000,11.190000,11.590000,11.550000,12.170000,11.350000,9.720000,9.487000,9.568000
Brunei Darussalam,BRN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.424000,6.658000,6.720000,6.897000,7.029000,6.965000,7.756000,8.559000,9.316000,9.224000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Latin America & the Caribbean (IDA & IBRD countries),TLA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.666859,7.064313,6.522478,6.413785,6.338548,6.150531,6.685651,7.858384,8.161817,8.137898
Timor-Leste,TLS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.180000,3.301000,3.201000,3.249000,3.326000,3.288000,3.343000,2.979000,2.963000,2.999000
Middle East & North Africa (IDA & IBRD countries),TMN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.347877,10.634479,11.415288,11.717683,11.212578,11.239425,11.450745,11.514831,11.389468,11.293507
Tonga,TON,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.125000,1.146000,1.134000,1.113000,1.135000,1.110000,1.080000,1.055000,1.003000,1.027000
South Asia (IDA & IBRD),TSA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.552167,2.368484,2.452512,2.689762,2.962370,2.798306,2.992566,2.929176,2.773212,2.750178
Sub-Saharan Africa (IDA & IBRD countries),TSS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.190139,6.322814,6.160723,6.024351,5.925104,5.896349,6.073460,6.249682,6.120978,6.096124
Trinidad and Tobago,TTO,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.648000,3.775000,3.248000,3.453000,2.460000,2.224000,2.211000,2.972000,2.817000,2.830000
Tunisia,TUN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.291000,13.049000,18.334000,17.629999,15.934000,15.058000,15.218000,15.514000,15.379000,15.478000
Turkey,TUR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.552000,10.660000,8.796000,8.149000,8.732000,9.880000,10.236000,10.839000,10.819000,10.895000
Tuvalu,TUV,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tanzania,TZA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.500000,3.035000,3.470000,3.240000,2.930000,2.125000,2.123000,2.095000,1.939000,1.932000
Uganda,UGA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.600000,3.680000,3.595000,3.551000,1.910000,1.888000,1.870000,1.792000,1.698000,1.742000
Ukraine,UKR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.840000,8.100000,7.860000,7.530000,7.170000,9.270000,9.140000,9.350000,9.510000,9.381000
Upper middle income,UMC,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.157953,5.893072,5.701646,5.690786,5.652736,5.615200,5.799850,6.054581,6.061633,6.049054
Uruguay,URY,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.740000,7.158000,6.307000,6.451000,6.444000,6.547000,7.488000,7.841000,7.890000,7.961000
United States,USA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.254000,9.633000,8.949000,8.069000,7.375000,6.168000,5.280000,4.869000,4.355000,3.933000
Uzbekistan,UZB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.040000,5.360000,4.960000,4.870000,4.860000,5.090000,5.150000,5.160000,4.972000,5.223000
St. Vincent and the Grenadines,VCT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.752001,19.916000,19.791000,19.719999,19.691000,19.687000,20.198999,20.065001,19.731001,19.761000
"Venezuela, RB",VEN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.050000,8.450000,6.902000,6.601000,7.540000,6.950000,6.820000,7.460000,7.422000,8.365000
British Virgin Islands,VGB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Virgin Islands (U.S.),VIR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.050000,9.242000,9.201000,9.309000,9.358000,9.154000,8.923000,8.706000,8.462000,8.410000
Vietnam,VNM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.737000,1.114000,0.999000,1.027000,1.252000,1.256000,1.859000,1.851000,1.886000,1.891000
Vanuatu,VUT,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.460000,5.636000,5.888000,6.051000,5.991000,5.870000,5.526000,5.694000,5.423000,5.409000
World,WLD,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.598770,5.474486,5.343200,5.351460,5.352923,5.189820,5.216667,5.215801,5.050056,4.953513
Samoa,WSM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.345000,5.524000,5.680000,8.752000,8.796000,8.720000,8.616000,8.606000,8.324000,8.325000
Kosovo,XKX,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Yemen, Rep.",YEM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.513000,12.905000,13.058000,13.252000,13.507000,13.467000,14.023000,13.524000,13.175000,12.934000
South Africa,ZAF,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.538000,24.693001,24.653000,24.732000,24.569000,24.898001,25.156000,26.551001,27.327000,26.958000
Zambia,ZMB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.623000,13.190000,10.200000,7.850000,7.801000,7.707000,7.446000,7.372000,7.206000,7.209000
Zimbabwe,ZWE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.034000,5.122000,5.368000,5.608000,5.623000,5.518000,5.438000,5.239000,4.943000,4.915000

In [20]:
unem_csv = unem_csv.drop(unem_csv.columns[1:50], axis =1)
unem_csv

2,Country Code,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0
Country Name,,,,,,,,,,,,,
Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,AFG,2.128000,2.494000,2.470000,2.275000,1.984000,1.692000,1.725000,1.735000,1.679000,1.634000,1.559000,1.542000
Angola,AGO,14.633000,12.044000,10.609000,9.089000,7.362000,7.359000,7.454000,7.429000,7.279000,7.281000,7.139000,7.253000
Albania,ALB,15.966000,13.060000,13.674000,14.086000,13.481000,13.376000,15.866000,17.490000,17.080000,15.220000,13.750000,13.898000
Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World,ARB,9.846743,9.472814,9.259066,9.178180,10.037677,10.233833,10.219504,10.218629,10.220711,9.967000,9.956021,9.942483
United Arab Emirates,ARE,2.467000,2.333000,2.699000,2.663000,2.494000,2.409000,2.292000,2.061000,1.836000,1.636000,2.463000,2.575000
Argentina,ARG,8.470000,7.837000,8.645000,7.714000,7.179000,7.217000,7.100000,7.268000,7.643000,8.016000,8.347000,9.483000
Armenia,ARM,9.812000,16.368000,18.740000,19.007999,18.443001,17.309999,16.179001,17.497999,18.261000,17.617001,17.827000,17.712000
American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Antigua and Barbuda,ATG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Australia,AUS,4.377000,4.234000,5.561000,5.211000,5.081000,5.224000,5.663000,6.078000,6.056000,5.711000,5.594000,5.387000
Austria,AUT,4.858000,4.128000,5.301000,4.820000,4.564000,4.865000,5.335000,5.620000,5.723000,6.014000,5.499000,4.786000
Azerbaijan,AZE,6.540000,6.050000,5.740000,5.630000,5.420000,5.190000,4.970000,4.910000,4.960000,5.000000,5.000000,5.220000
Burundi,BDI,1.640000,1.634000,1.795000,1.800000,1.766000,1.712000,1.674000,1.570000,1.592000,1.566000,1.501000,1.528000
Belgium,BEL,7.458000,6.976000,7.908000,8.292000,7.140000,7.542000,8.425000,8.523000,8.482000,7.830000,7.086000,6.323000
Benin,BEN,0.732000,0.788000,0.967000,1.040000,2.646000,2.735000,2.666000,2.541000,2.463000,2.419000,2.180000,2.125000
Burkina Faso,BFA,3.300000,3.594000,4.397000,4.909000,5.293000,5.809000,6.278000,6.479000,6.704000,6.364000,6.015000,6.059000
Bangladesh,BGD,3.768000,4.077000,5.000000,3.379000,3.718000,4.048000,4.426000,4.411000,4.416000,4.350000,4.372000,4.308000
Bulgaria,BGR,6.878000,5.609000,6.817000,10.279000,11.260000,12.270000,12.941000,11.424000,9.143000,7.575000,6.164000,5.261000
Bahrain,BHR,0.838000,0.835000,1.069000,1.130000,1.140000,1.200000,1.216000,1.149000,1.076000,1.013000,0.947000,0.962000
"Bahamas, The",BHS,7.880000,8.180000,14.250000,14.540000,14.520000,14.020000,16.180000,13.800000,12.000000,12.700000,12.381000,11.850000
Bosnia and Herzegovina,BIH,28.983999,23.405001,24.068001,27.312000,27.582001,28.010000,27.450001,27.517000,27.650000,25.410000,20.469999,20.839001
Belarus,BLR,6.781000,6.122000,6.100000,6.061000,6.075000,6.038000,5.935000,5.893000,5.913000,5.840000,5.650000,5.708000
Belize,BLZ,8.510000,8.180000,10.115000,11.659000,12.758000,14.270000,11.700000,11.570000,9.970000,7.910000,9.000000,9.368000
Bermuda,BMU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bolivia,BOL,2.723000,2.603000,2.863000,2.577000,2.219000,2.048000,2.394000,2.007000,3.066000,3.056000,3.233000,3.258000
Brazil,BRA,8.327000,7.343000,8.522000,7.726000,6.917000,7.193000,6.985000,6.670000,8.437000,11.609000,12.827000,12.544000
Barbados,BRB,7.410000,8.120000,10.020000,10.690000,11.190000,11.590000,11.550000,12.170000,11.350000,9.720000,9.487000,9.568000
Brunei Darussalam,BRN,5.624000,5.697000,6.424000,6.658000,6.720000,6.897000,7.029000,6.965000,7.756000,8.559000,9.316000,9.224000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Latin America & the Caribbean (IDA & IBRD countries),TLA,6.954349,6.569012,7.666859,7.064313,6.522478,6.413785,6.338548,6.150531,6.685651,7.858384,8.161817,8.137898
Timor-Leste,TLS,3.103000,2.964000,3.180000,3.301000,3.201000,3.249000,3.326000,3.288000,3.343000,2.979000,2.963000,2.999000
Middle East & North Africa (IDA & IBRD countries),TMN,10.360048,10.051254,10.347877,10.634479,11.415288,11.717683,11.212578,11.239425,11.450745,11.514831,11.389468,11.293507
Tonga,TON,0.988000,0.957000,1.125000,1.146000,1.134000,1.113000,1.135000,1.110000,1.080000,1.055000,1.003000,1.027000
South Asia (IDA & IBRD),TSA,2.366704,2.288566,2.552167,2.368484,2.452512,2.689762,2.962370,2.798306,2.992566,2.929176,2.773212,2.750178
Sub-Saharan Africa (IDA & IBRD countries),TSS,6.258844,5.848566,6.190139,6.322814,6.160723,6.024351,5.925104,5.896349,6.073460,6.249682,6.120978,6.096124
Trinidad and Tobago,TTO,3.115000,3.107000,3.648000,3.775000,3.248000,3.453000,2.460000,2.224000,2.211000,2.972000,2.817000,2.830000
Tunisia,TUN,12.365000,12.444000,13.291000,13.049000,18.334000,17.629999,15.934000,15.058000,15.218000,15.514000,15.379000,15.478000
Turkey,TUR,8.868000,9.710000,12.552000,10.660000,8.796000,8.149000,8.732000,9.880000,10.236000,10.839000,10.819000,10.895000
Tuvalu,TUV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tanzania,TZA,2.693000,2.358000,2.500000,3.035000,3.470000,3.240000,2.930000,2.125000,2.123000,2.095000,1.939000,1.932000
Uganda,UGA,2.256000,2.662000,3.600000,3.680000,3.595000,3.551000,1.910000,1.888000,1.870000,1.792000,1.698000,1.742000
Ukraine,UKR,6.350000,6.360000,8.840000,8.100000,7.860000,7.530000,7.170000,9.270000,9.140000,9.350000,9.510000,9.381000
Upper middle income,UMC,5.634907,5.652551,6.157953,5.893072,5.701646,5.690786,5.652736,5.615200,5.799850,6.054581,6.061633,6.049054
Uruguay,URY,9.403000,8.025000,7.740000,7.158000,6.307000,6.451000,6.444000,6.547000,7.488000,7.841000,7.890000,7.961000
United States,USA,4.622000,5.784000,9.254000,9.633000,8.949000,8.069000,7.375000,6.168000,5.280000,4.869000,4.355000,3.933000
Uzbekistan,UZB,4.990000,4.890000,5.040000,5.360000,4.960000,4.870000,4.860000,5.090000,5.150000,5.160000,4.972000,5.223000
St. Vincent and the Grenadines,VCT,18.794001,18.799999,19.752001,19.916000,19.791000,19.719999,19.691000,19.687000,20.198999,20.065001,19.731001,19.761000
"Venezuela, RB",VEN,7.279000,6.245000,8.050000,8.450000,6.902000,6.601000,7.540000,6.950000,6.820000,7.460000,7.422000,8.365000
British Virgin Islands,VGB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Virgin Islands (U.S.),VIR,8.188000,8.174000,9.050000,9.242000,9.201000,9.309000,9.358000,9.154000,8.923000,8.706000,8.462000,8.410000
Vietnam,VNM,2.026000,2.380000,1.737000,1.114000,0.999000,1.027000,1.252000,1.256000,1.859000,1.851000,1.886000,1.891000
Vanuatu,VUT,5.373000,5.058000,5.460000,5.636000,5.888000,6.051000,5.991000,5.870000,5.526000,5.694000,5.423000,5.409000
World,WLD,4.936556,4.944230,5.598770,5.474486,5.343200,5.351460,5.352923,5.189820,5.216667,5.215801,5.050056,4.953513
Samoa,WSM,4.751000,4.769000,5.345000,5.524000,5.680000,8.752000,8.796000,8.720000,8.616000,8.606000,8.324000,8.325000
Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Yemen, Rep.",YEM,11.338000,11.343000,12.513000,12.905000,13.058000,13.252000,13.507000,13.467000,14.023000,13.524000,13.175000,12.934000
South Africa,ZAF,26.666000,22.433001,23.538000,24.693001,24.653000,24.732000,24.569000,24.898001,25.156000,26.551001,27.327000,26.958000
Zambia,ZMB,9.987000,7.930000,10.623000,13.190000,10.200000,7.850000,7.801000,7.707000,7.446000,7.372000,7.206000,7.209000
Zimbabwe,ZWE,4.161000,4.450000,5.034000,5.122000,5.368000,5.608000,5.623000,5.518000,5.438000,5.239000,4.943000,4.915000

In [21]:
unem_csv = unem_csv.loc[["Canada","United States","Mexico","Brazil","Korea, Rep.","Philippines",
                        "China","Cambodia","Germany","Russian Federation","Greece"]]
unem_csv

2,Country Code,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0
Country Name,,,,,,,,,,,,,
Canada,CAN,6.036,6.137,8.344,8.056,7.511,7.292000,7.074,6.914000,6.906000,6.999,6.340000,5.920000
United States,USA,4.622,5.784,9.254,9.633,8.949,8.069000,7.375,6.168000,5.280000,4.869,4.355000,3.933000
Mexico,MEX,3.628,3.874,5.356,5.303,5.170,4.887000,4.914,4.809000,4.313000,3.859,3.420000,3.322000
Brazil,BRA,8.327,7.343,8.522,7.726,6.917,7.193000,6.985,6.670000,8.437000,11.609,12.827000,12.544000
"Korea, Rep.",KOR,3.200,3.200,3.600,3.700,3.400,3.200000,3.100,3.500000,3.600000,3.700,3.700000,3.795000
Philippines,PHL,3.434,3.720,3.858,3.605,3.592,3.504000,3.497,3.600000,3.026000,2.708,2.552000,2.515000
China,CHN,4.300,4.600,4.700,4.500,4.500,4.600000,4.600,4.600000,4.600000,4.500,4.400000,4.417000
Cambodia,KHM,1.168,1.151,1.281,1.377,1.318,1.279000,1.284,1.232000,1.196000,1.131,1.062000,1.048000
Germany,DEU,8.658,7.524,7.742,6.966,5.824,5.379000,5.231,4.981000,4.624000,4.122,3.746000,3.425000
Russian Federation,RUS,6.002,6.205,8.301,7.369,6.536,5.436000,5.458,5.160000,5.571000,5.559,5.212000,4.744000
Greece,GRC,8.396,7.760,9.616,12.713,17.865,24.438999,27.466,26.490999,24.896999,23.539,21.488001,19.207001

In [22]:

unem_csv = unem_csv.reset_index()

2,Country Name,Country Code,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0
0,Canada,CAN,6.036,6.137,8.344,8.056,7.511,7.292000,7.074,6.914000,6.906000,6.999,6.340000,5.920000
1,United States,USA,4.622,5.784,9.254,9.633,8.949,8.069000,7.375,6.168000,5.280000,4.869,4.355000,3.933000
2,Mexico,MEX,3.628,3.874,5.356,5.303,5.170,4.887000,4.914,4.809000,4.313000,3.859,3.420000,3.322000
3,Brazil,BRA,8.327,7.343,8.522,7.726,6.917,7.193000,6.985,6.670000,8.437000,11.609,12.827000,12.544000
4,"Korea, Rep.",KOR,3.200,3.200,3.600,3.700,3.400,3.200000,3.100,3.500000,3.600000,3.700,3.700000,3.795000
5,Philippines,PHL,3.434,3.720,3.858,3.605,3.592,3.504000,3.497,3.600000,3.026000,2.708,2.552000,2.515000
6,China,CHN,4.300,4.600,4.700,4.500,4.500,4.600000,4.600,4.600000,4.600000,4.500,4.400000,4.417000
7,Cambodia,KHM,1.168,1.151,1.281,1.377,1.318,1.279000,1.284,1.232000,1.196000,1.131,1.062000,1.048000
8,Germany,DEU,8.658,7.524,7.742,6.966,5.824,5.379000,5.231,4.981000,4.624000,4.122,3.746000,3.425000
9,Russian Federation,RUS,6.002,6.205,8.301,7.369,6.536,5.436000,5.458,5.160000,5.571000,5.559,5.212000,4.744000
10,Greece,GRC,8.396,7.760,9.616,12.713,17.865,24.438999,27.466,26.490999,24.896999,23.539,21.488001,19.207001

In [23]:
export = unem_csv.to_csv(r'C:\\Users\\carlo\\Desktop\\UNEM1.csv', index = None, header = True )